
import java.awt.ItemSelectable;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kevin
 */
public class Login extends javax.swing.JFrame {

    ArbolB usuario;
    ArbolB conductor;
    HashTable tablaHash;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }
    
    public Login(ArbolB usuario, ArbolB conductor, HashTable tablaHash) {
        this.usuario = usuario;
        this.conductor = conductor;
        this.tablaHash = tablaHash;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jlbNickName = new javax.swing.JLabel();
        jlbPassWord = new javax.swing.JLabel();
        jtNickName = new javax.swing.JTextField();
        jbAceptar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jpPassWord = new javax.swing.JPasswordField();
        jcbTipoUsuario = new javax.swing.JComboBox<>();
        jbRegistrarUsuario = new javax.swing.JButton();
        jbRegistrarConductor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jlbPassWord1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SafeWay");

        jlbNickName.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jlbNickName.setText("NickName");
        jlbNickName.setMaximumSize(new java.awt.Dimension(70, 20));
        jlbNickName.setMinimumSize(new java.awt.Dimension(70, 20));
        jlbNickName.setPreferredSize(new java.awt.Dimension(70, 20));

        jlbPassWord.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jlbPassWord.setText("PassWord");

        jtNickName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNickNameActionPerformed(evt);
            }
        });

        jbAceptar.setText("Aceptar");
        jbAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAceptarActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jcbTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuario", "Conductor", "Administrador" }));
        jcbTipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTipoUsuarioActionPerformed(evt);
            }
        });

        jbRegistrarUsuario.setText("Usuario");
        jbRegistrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRegistrarUsuarioActionPerformed(evt);
            }
        });

        jbRegistrarConductor.setText("Conductor");
        jbRegistrarConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRegistrarConductorActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setText("    Registrar");

        jlbPassWord1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jlbPassWord1.setText("Tipo Usuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbPassWord, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jlbPassWord1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jpPassWord, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbNickName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtNickName, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbRegistrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbRegistrarConductor)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbNickName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtNickName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpPassWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbPassWord, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbPassWord1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbTipoUsuario))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAceptar)
                    .addComponent(jbCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbRegistrarUsuario)
                    .addComponent(jbRegistrarConductor))
                .addContainerGap())
        );

        jtNickName.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtNickNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNickNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNickNameActionPerformed

    private void jbAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAceptarActionPerformed
        
        jcbTipoUsuario.getSelectedIndex();//0 usuario, 1 conductor, 2 administrador
        
        if(jtNickName.getText().equals("") || jpPassWord.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Hay campos vacios");
            //eliminar despues de las pruebas de administrador
            //Admin admin = new Admin(usuario, conductor, tablaHash);
            //admin.setLocationRelativeTo(null);
            //admin.setVisible(true);
            //dispose();
        }else if(jtNickName.getText().toLowerCase().equals("andree_avalos") && jpPassWord.getText().equalsIgnoreCase("admin") && jcbTipoUsuario.getSelectedIndex() == 2){
            JOptionPane.showMessageDialog(this, "Administrador");
            Admin admin = new Admin(usuario, conductor, tablaHash);
            admin.setLocationRelativeTo(null);
            admin.setVisible(true);
            //dispose();
        }
        //usuario normal
        else if(jcbTipoUsuario.getSelectedIndex() == 0){
            Usuario usuarioCargado = null;
            //Convierto a sha256 y lo envío al metodo
            String pass = convertirSHA256(jpPassWord.getText());
            usuarioCargado = usuario.iniciarSesion(jtNickName.getText(), pass);
            if(usuarioCargado == null){
                System.out.println("no se encontro el usuario");
                JOptionPane.showMessageDialog(this, "No se encontro el usuario");
            }else{
                System.out.println("Encontre el usuario " + usuarioCargado.usuario);
                //UsuarioNormal cargar = new UsuarioNormal(usuarioCargado,usuario,conductor);
                UsuarioNormal cargar = new UsuarioNormal(usuarioCargado, usuario, tablaHash);
                cargar.setLocationRelativeTo(null);
                cargar.setVisible(true);
            }
        }
        //usuario conductor
        else if(jcbTipoUsuario.getSelectedIndex() == 1){
            Usuario usuarioCargado = null;
            //Convierto a sha256 y lo envío al metodo
            String pass = convertirSHA256(jpPassWord.getText());
            usuarioCargado = conductor.iniciarSesion(jtNickName.getText(), pass);
            if(usuarioCargado != null){
                System.out.println("Encontre el usuario " + usuarioCargado.usuario);
                //UsuarioConductor cargar = new UsuarioConductor(usuarioCargado, usuario, conductor);
                UsuarioConductor cargar = new UsuarioConductor(usuarioCargado, conductor);
                cargar.setLocationRelativeTo(null);
                cargar.setVisible(true);
                //dispose();
            }else{
                System.out.println("no se encontro el usuario");
                JOptionPane.showMessageDialog(this, "No se encontro el usuario");
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "El NickName, PassWord o tipo de Usuario es incorrecto");
        }
        //limpiar los campos de texto
        jtNickName.setText("");
        jpPassWord.setText("");
        jcbTipoUsuario.setSelectedIndex(0);
    }//GEN-LAST:event_jbAceptarActionPerformed

    public static String convertirSHA256(String password) {
	MessageDigest md = null;
	try {
		md = MessageDigest.getInstance("SHA-256");
	} 
	catch (NoSuchAlgorithmException e) {		
		e.printStackTrace();
		return null;
	}
	    
	byte[] hash = md.digest(password.getBytes());
	StringBuffer sb = new StringBuffer();
	    
	for(byte b : hash) {        
		sb.append(String.format("%02x", b));
	}
	    
	return sb.toString();
    }
    
    
    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jcbTipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTipoUsuarioActionPerformed
        /*if(jcbTipoUsuario.getSelectedIndex() == 0){
            System.out.println("Usuario");
        }else if(jcbTipoUsuario.getSelectedIndex() == 1){
            System.out.println("Conductor");
        }else{
            System.out.println("administrador");
        }*/
    }//GEN-LAST:event_jcbTipoUsuarioActionPerformed

    private void jbRegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRegistrarUsuarioActionPerformed
        //Registrar usuario normal (true)
        RegistrarUsuario registrar = new RegistrarUsuario(usuario, conductor, true);
        registrar.setLocationRelativeTo(null);
        registrar.setVisible(true);
    }//GEN-LAST:event_jbRegistrarUsuarioActionPerformed

    private void jbRegistrarConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRegistrarConductorActionPerformed
        //registras usuario conductor (false)
        RegistrarUsuario registrar = new RegistrarUsuario(usuario, conductor, false);
        registrar.setLocationRelativeTo(null);
        registrar.setVisible(true);
    }//GEN-LAST:event_jbRegistrarConductorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbAceptar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbRegistrarConductor;
    private javax.swing.JButton jbRegistrarUsuario;
    private javax.swing.JComboBox<String> jcbTipoUsuario;
    private javax.swing.JLabel jlbNickName;
    private javax.swing.JLabel jlbPassWord;
    private javax.swing.JLabel jlbPassWord1;
    private javax.swing.JPasswordField jpPassWord;
    private javax.swing.JTextField jtNickName;
    // End of variables declaration//GEN-END:variables
}
